#!/bin/bash

eval set -- $(getopt -o +w:hpo: -- "$@")
unset PODMAN
unset OUTPUT_LOG

while [ $1 != '--' ]; do case $1 in
	-w) WORKDIR_CURRENT="$2"; shift ; shift ;;
	-p) PODMAN="y"; shift ;;
	-o) OUTPUT_LOG="$2"; shift ; shift ;;
        -h) cat >&2 <<EOF
usage: $0 options [--] orca_args ...

options are:
        -w              directory relative to outside work directory for orca evaluation
	-p		use podman instead of docker
	-o		specify output log file for orca output
EOF
        exit 1;;
        --) shift; break ;;
esac; done

while [ "$1" == '--' ]; do shift; done

if [ -z "$SCRATCHDIR" ]; then
	echo Warning: SCRATCHDIR not set, / may be filled up >&2
else
	TMPDIR=$SCRATCHDIR
	export TMPDIR
fi

if [ -z "$WORKDIR_OUTSIDE" ]; then
	WORKDIR_OUTSIDE=${WORK:-$PWD}
fi

output_log=$PWD/podmand.log
if [ -n "$OUTPUT_LOG" ]; then
	output_log=${WORKDIR_OUTSIDE}${WORKDIR_CURRENT}${OUTPUT_LOG}
fi


VOLUME=${WORKDIR_OUTSIDE}${WORKDIR_CURRENT}:/tmp
IMAGE="spectraes/pipeline_orca:latest"

if [ -n "$PODMAN" ]; then
podman="podman"
podman_run="$podman run --privileged --hostname ${HOSTNAME}"

cat - >/tmp/orca-podman.$$ <<EOF
#!/bin/bash
EOF
	echo -n /opt/orca/orca >>/tmp/orca-podman.$$
	#echo -n ls -la >>/tmp/orca-podman.$$
	for a in "$@"; do
		echo -n " "\"$a\" >>/tmp/orca-podman.$$
	done
	echo >>/tmp/orca-podman.$$

	chmod +x /tmp/orca-podman.$$
	cat /tmp/orca-podman.$$

	$podman_run -v /:/host -v $VOLUME -ti $IMAGE /host/tmp/orca-podman.$$ > $output_log

	rm /tmp/orca-podman.$$
else
	docker run -v /:/host -v $VOLUME -ti $IMAGE /opt/orca/orca $@
fi

